# Generated by Django 3.2.5 on 2021-07-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
