# Generated by Django 3.2.5 on 2021-07-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_jobdetails'),
        ('employee', '0002_alter_employeeprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.jobdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeeprofile')),
            ],
        ),
    ]
