# Generated by Django 3.2.5 on 2021-08-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_neededfilesmachinetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neededfilesmachinetest',
            name='compressed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
