# Generated by Django 3.2.5 on 2021-07-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20210728_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
