# Generated by Django 3.2.5 on 2021-08-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_replymachinetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymachinetest',
            name='machinetest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.machinetestfiles'),
        ),
    ]
