# Generated by Django 3.2.5 on 2021-07-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompanies',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
