# Generated by Django 3.1.7 on 2021-07-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercompanies_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
