# Generated by Django 3.2.5 on 2021-07-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210723_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompanies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
