# Generated by Django 3.2.5 on 2021-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companysocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysocial',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companysocial',
            name='google',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
