# Generated by Django 3.2.5 on 2021-08-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyextra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyextra',
            name='posted_job',
        ),
    ]
