# Generated by Django 3.2.5 on 2021-08-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
